language: java

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
env:
  global:
  - PGPORT=5432

before_script:
  - psql -U postgres -c "create database colaboreitor"
  - psql -U postgres -c "create extension postgis"

after_success:
  - mvn cobertura:cobertura coveralls:report

