language: java

services:
  - postgresql

before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database travis_ci_test;' -U postgres

after_success:
  -  mvn cobertura:cobertura coveralls:report

