language: java

services:
  postgresql:
    ports:
      - "5432"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

before_script:
  - psql -U postgres -c "create database colaboreitor"
  - psql -U postgres -c "create extension postgis"

after_success:
  - mvn cobertura:cobertura coveralls:report

