language: java

services:
  postgresql:
    ports:
      - "5433"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

env:
  global:
    - PGPORT=5433

sudo: true

before_script:
  - sudo netstat -tupan
  - psql -U postgres -c "create database colaboreitor"
  - psql -U postgres -c "create extension postgis"
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres

after_success:
  - mvn cobertura:cobertura coveralls:report

